create or replace view OLIST_DB.OLIST_SCHEMA.BASE_ORDER_ITEMS(
	ORDER_ID,
	PRODUCT_ID,
	SELLER_ID,
	ORDER_ITEM_ID,
	PRICE,
	FREIGHT_VALUE,
	GMV_ITEM,
	ORDER_STATUS,
	ORDER_PURCHASE_TIMESTAMP,
	ORDER_APPROVED_AT,
	ORDER_DELIVERED_CUSTOMER_DATE,
	ORDER_ESTIMATED_DELIVERY_DATE,
	PRODUCT_CATEGORY_NAME
) as
SELECT 
  foi.ORDER_ID,
  foi.PRODUCT_ID,
  foi.SELLER_ID,
  foi.ORDER_ITEM_ID,
  foi.PRICE,
  foi.FREIGHT_VALUE,
  (foi.PRICE + foi.FREIGHT_VALUE) AS GMV_ITEM,
  do.ORDER_STATUS,
  do.ORDER_PURCHASE_TIMESTAMP,
  do.ORDER_APPROVED_AT,
  do.ORDER_DELIVERED_CUSTOMER_DATE,
  do.ORDER_ESTIMATED_DELIVERY_DATE,
  dp.PRODUCT_CATEGORY_NAME
FROM OLIST_DB.OLIST_SCHEMA.FACT_ORDER_ITEMS foi
JOIN OLIST_DB.OLIST_SCHEMA.DIM_ORDERS do
  ON do.ORDER_ID = foi.ORDER_ID
LEFT JOIN OLIST_DB.OLIST_SCHEMA.DIM_PRODUCTS dp
  ON dp.PRODUCT_ID = foi.PRODUCT_ID;