-- Seller Performance view: seller-level monthly metrics
CREATE OR REPLACE VIEW OLIST_DB.OLIST_SCHEMA.VW_SELLER_MONTHLY AS
WITH base AS (
  SELECT 
    DATE_TRUNC('month', ORDER_PURCHASE_TIMESTAMP) AS MONTH,
    SELLER_ID,
    COUNT(DISTINCT ORDER_ID) AS ORDERS,
    COUNT(*) AS ITEMS,
    SUM(PRICE + FREIGHT_VALUE) AS GMV,
    AVG(CASE WHEN ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL AND ORDER_DELIVERED_CUSTOMER_DATE <= ORDER_ESTIMATED_DELIVERY_DATE THEN 1 ELSE 0 END) AS ON_TIME_RATE
  FROM OLIST_DB.OLIST_SCHEMA.BASE_ORDER_ITEMS
  GROUP BY 1, 2
), reviews AS (
  SELECT foi.SELLER_ID, AVG(dr.REVIEW_SCORE) AS AVG_REVIEW
  FROM OLIST_DB.OLIST_SCHEMA.FACT_ORDER_ITEMS foi
  JOIN OLIST_DB.OLIST_SCHEMA.DIM_REVIEWS dr ON dr.ORDER_ID = foi.ORDER_ID
  GROUP BY foi.SELLER_ID
)
SELECT 
  b.MONTH,
  b.SELLER_ID,
  b.ORDERS,
  b.ITEMS,
  b.GMV,
  b.ON_TIME_RATE,
  r.AVG_REVIEW
FROM base b
LEFT JOIN reviews r ON r.SELLER_ID = b.SELLER_ID
ORDER BY b.MONTH, b.SELLER_ID;